### ISSUE TITLE
como uso esse código?

### ISSUE THREAD

**Issue by ghost** [joanezandrades/excelbus#1]

**Comment by jnz93** [comment]
Bom dia, Lucas. Tudo bem? Desculpe a demora, estive ausente alguns dias devido a uma situação de saúde. 

Cara, na verdade o código atual está obsoleto. Este é um plugin foi desenvolvido há uns 4-5 anos atrás para uma empresa de viação que resolvia especificamente o caso dela. 
Portanto este código só vai funcionar para aquele caso específico. Não fiz alterações ou adaptações posteriores no sistema. 

Porém, ficarei feliz em ajudar a desenvolver uma ferramenta semelhante. Caso você precise de ajuda podemos conversar. Me chama lá no whatsapp (45) 988304602.

**Comment by jnz93** [comment]
Claro, perfeito. Mas qual parte do sistema te interessou? 

Pelo o que entendi, me corrija se eu estiver errado, você pretende ler planilhas, ou algo do tipo, para alimentar uma rede de compartilhamento de informações? 

Me da mais detalhes, quem sabe posso ajudar em alguma coisa.
